/*******************************************************************************
* File Name: cycfg_connectivity.h
*
* Description:
* Establishes all necessary connections between hardware elements.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_CONNECTIVITY_H)
#define CYCFG_CONNECTIVITY_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "notices.h"
void init_connectivity(void);

#define ioss_0__port_6__pin_4__HSIOM P6_4_CPUSS_SWJ_SWO_TDO
#define ioss_0__port_6__pin_6__HSIOM P6_6_CPUSS_SWJ_SWDIO_TMS
#define ioss_0__port_6__pin_7__HSIOM P6_7_CPUSS_SWJ_SWCLK_TCLK
#define LED_HSIOM P1_1_TCPWM0_LINE_COMPL3
#define UART_RX_HSIOM P5_0_SCB5_UART_RX
#define UART_TX_HSIOM P5_1_SCB5_UART_TX

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_CONNECTIVITY_H */
