/*******************************************************************************
* File Name: notices.h
*
* Description:
* Contains warnings and errors that occurred while generating code for the
* design.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(NOTICES_H_H)
#define NOTICES_H_H


#endif /* NOTICES_H_H */
